## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters

## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: cluster.local
## @param extraDeploy Array of extra objects to deploy with the release
##
extraDeploy: []

image:
  registry: docker.io
  repository: gradiant/ueransim
  tag: 3.2.6
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []
  ## Enable debug mode
  ##
  debug: false

name: ueransim-gnb
amf:
  # if set amf.ip takes precedence over amf.hostname
  ip: ""
  hostname: oai-amf
interfaces:
  n2:
    dev: eth0
  n3:
    dev: eth0
  radio:
    dev: eth0
mcc: '208'
mnc: '95'
sst: 1 #for UE 
#sd: "0x000002" #for UE
#tac: '0001'

hpa:
 enabled: false

resources:
  limits: {}
  requests: {}
podSecurityContext:
  enabled: false
containerSecurityContext:
  enabled: false
podLabels: {}
podAnnotations: {}
affinity: {}
nodeSelector: {}
tolerations: []

ues:
  enabled: false
  count: 100
  initialMSISDN: '0000000034'
  key: 0C0A34601D4F07677303652C0462535B
  op: 63bfa50ee6523365ff14c1f45f88737d
  opType: OPC
  apnList:
    - type: 'IPv4'
      apn: 'oai'
      slice:
        sst: 1
        #sd: "0x000002"
      emergency: false
  resources:
    limits: {}
    requests: {}
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  podLabels: {}
  podAnnotations: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
